name: Sync to Hugging Face Spaces

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  sync-to-hub:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          lfs: true

      - name: Push to Hugging Face
        env:
          HF_TOKEN: ${{ secrets.HF_TOKEN }}
        run: |
          git config --global user.email "poojamallavarapu@users.noreply.github.com"
          git config --global user.name "Pooja Mallavarapu"
          git remote add space https://Poojamallavarapu:$HF_TOKEN@huggingface.co/spaces/miniorange/aria-cybersecurity
          git push --force space main
